name: Publish AUR Package

permissions:
  contents: read
  
on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string
    secrets:
      AUR_SSH_PRIVATE_KEY:
        description: 'SSH private key for AUR'
        required: true

jobs:
    publish_aur_package:
        name: Publish AUR package
        outputs:
            version: ${{ steps.gen_template.outputs.version }}

        runs-on: ubuntu-latest

        continue-on-error: true

        steps:
            - uses: actions/checkout@v5
              with:
                fetch-depth: 0
            
            - name: Resolve latest tag
              id: resolve_tag
              run: |
                    LATEST_TAG=${{ inputs.version }}
                    if [[ -z "$LATEST_TAG" ]]; then
                      git fetch --tags
                      LATEST_TAG=$(git describe --tags --abbrev=0 | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g')
                    fi
                    echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
                    echo "latest=$LATEST_TAG" >> $GITHUB_OUTPUT
                    echo "Latest tag: $LATEST_TAG"

            - name: Generate PKGBUILD
              id: gen_template
              run: |
                  sed -i "s/pkgver=0.0.0/pkgver=$LATEST_TAG/" PKGBUILD

            - name: Publish SJMCL to the AUR
              uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
              with:
                  pkgname: sjmcl-bin
                  pkgbuild: ${{ github.workspace }}/PKGBUILD
                  assets: ${{ github.workspace }}/LICENSE.EXTRA
                  commit_username: SJMC
                  commit_email: launcher@sjmc.club
                  ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
                  commit_message: ${{ steps.resolve_tag.outputs.latest }}
                  updpkgsums: "true"
                  ssh_keyscan_types: rsa,ecdsa,ed25519
